# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: live.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'live.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlive.proto\x12\x04live\"+\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06volume\x18\x02 \x01(\x01\"\xa9\x01\n\x0cLiveSnapshot\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x13\n\x0b\x65xchange_ts\x18\x03 \x01(\t\x12\x11\n\tingest_ts\x18\x04 \x01(\t\x12\x1e\n\x04\x62ids\x18\x05 \x03(\x0b\x32\x10.live.PriceLevel\x12\x1e\n\x04\x61sks\x18\x06 \x03(\x0b\x32\x10.live.PriceLevel\x12\x11\n\tmid_price\x18\x07 \x01(\x01\"\"\n\x10SubscribeRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"%\n\x13\x43hangeSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"8\n\x14\x43hangeSymbolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x99\x01\n\x0fLiveFeedService\x12?\n\x0fStreamSnapshots\x12\x16.live.SubscribeRequest\x1a\x12.live.LiveSnapshot0\x01\x12\x45\n\x0c\x43hangeSymbol\x12\x19.live.ChangeSymbolRequest\x1a\x1a.live.ChangeSymbolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'live_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICELEVEL']._serialized_start=20
  _globals['_PRICELEVEL']._serialized_end=63
  _globals['_LIVESNAPSHOT']._serialized_start=66
  _globals['_LIVESNAPSHOT']._serialized_end=235
  _globals['_SUBSCRIBEREQUEST']._serialized_start=237
  _globals['_SUBSCRIBEREQUEST']._serialized_end=271
  _globals['_CHANGESYMBOLREQUEST']._serialized_start=273
  _globals['_CHANGESYMBOLREQUEST']._serialized_end=310
  _globals['_CHANGESYMBOLRESPONSE']._serialized_start=312
  _globals['_CHANGESYMBOLRESPONSE']._serialized_end=368
  _globals['_LIVEFEEDSERVICE']._serialized_start=371
  _globals['_LIVEFEEDSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
