# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"+\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06volume\x18\x02 \x01(\x01\"z\n\x08Snapshot\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12#\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x15.analytics.PriceLevel\x12#\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x15.analytics.PriceLevel\x12\x11\n\tmid_price\x18\x04 \x01(\x01\":\n\x07\x41nomaly\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x88\x03\n\x11ProcessedSnapshot\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x11\n\tmid_price\x18\x02 \x01(\x01\x12\x0e\n\x06spread\x18\x03 \x01(\x01\x12\x0b\n\x03ofi\x18\x04 \x01(\x01\x12\x0b\n\x03obi\x18\x05 \x01(\x01\x12%\n\tanomalies\x18\x06 \x03(\x0b\x32\x12.analytics.Anomaly\x12\x12\n\nmicroprice\x18\x07 \x01(\x01\x12\x12\n\ndivergence\x18\x08 \x01(\x01\x12\x18\n\x10\x64irectional_prob\x18\t \x01(\x01\x12\x0c\n\x04vpin\x18\n \x01(\x01\x12\x0e\n\x06regime\x18\x0b \x01(\x05\x12\x14\n\x0cregime_label\x18\x0c \x01(\t\x12\x10\n\x08\x62\x65st_bid\x18\r \x01(\x01\x12\x10\n\x08\x62\x65st_ask\x18\x0e \x01(\x01\x12\r\n\x05q_bid\x18\x0f \x01(\x01\x12\r\n\x05q_ask\x18\x10 \x01(\x01\x12\x11\n\tgap_count\x18\x11 \x01(\x05\x12\x1a\n\x12gap_severity_score\x18\x12 \x01(\x01\x12\x15\n\rspoofing_risk\x18\x13 \x01(\x01\x32X\n\x10\x41nalyticsService\x12\x44\n\x0fProcessSnapshot\x12\x13.analytics.Snapshot\x1a\x1c.analytics.ProcessedSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICELEVEL']._serialized_start=30
  _globals['_PRICELEVEL']._serialized_end=73
  _globals['_SNAPSHOT']._serialized_start=75
  _globals['_SNAPSHOT']._serialized_end=197
  _globals['_ANOMALY']._serialized_start=199
  _globals['_ANOMALY']._serialized_end=257
  _globals['_PROCESSEDSNAPSHOT']._serialized_start=260
  _globals['_PROCESSEDSNAPSHOT']._serialized_end=652
  _globals['_ANALYTICSSERVICE']._serialized_start=654
  _globals['_ANALYTICSSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)

